language: csharp 
sudo: false
dotnet: 2.1.401
solution: ./src/GlobalPhone.sln
install:
  - dotnet restore ./src/GlobalPhone.sln

script: 
  - dotnet test ./src/GlobalPhone.Tests/GlobalPhone.Tests.csproj --framework netcoreapp2.1
branches:
  only:
    - master